services:
  v2t:
    build: .
    container_name: v2t
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/.venv
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
