name: voice2text

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: create venv
        run: python3.11 -m venv .venv
      
      - name: install ruff
        run: .venv/bin/pip install ruff
      
      - name: run ruff check
        run: .venv/bin/ruff check .
      
      - name: check formatting
        run: .venv/bin/ruff format --check .
